baseURL = "http://blog.cloudalbania.com/"
languageCode = "en-us"
title = "CloudAlbania Blog"
theme = "soho"
description = "Personal blog where I cover my experiences and best practices with System Administration and DevOps"

summarylength = 10
enableEmoji = true

googleAnalytics = 'UA-36283915-1'

[params]
author = "Besmir Zanaj"
description = "CloudAlbania Blog"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/profile.png"

copyright = "Besmir Zanaj"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"


  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/besmirzanaj/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/besmirzanaj"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/besmirzanaj"

[menu]
  
  [[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

#   [[menu.main]]
#     name = "About"
#     identifier = "about"
#     weight = 300
#     url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4