baseURL = "https://cloudalbania.com/"
languageCode = "en-us"
title = "Besmir Zanaj"
theme = "m10c"
pagination = 100

#summarylength = 10
enableEmoji = true

# Analytics section
googleAnalytics = 'UA-36283915-1'

#  theme params
[params]
author = "Besmir Zanaj"
description = "Personal blog where I cover my experiences and best practices with System Administration and DevOps"
avatar = "/profile.png"
copyright = "Besmir Zanaj"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
favicon = "/favicon.ico"

  [params.style]
  # darkestColor = "#d35050"
  # darkColor = "#212121"
  # lightColor = "#f5e3e0"
  # lightestColor = "#f5f5f5"
  # primaryColor = "#ffffff"

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/besmirzanaj"

  [[params.social]]
    icon = "linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/besmirzanaj/"

  [[params.social]]
    icon = "twitter"
    title = "Twitter"
    url = "https://twitter.com/besmirzanaj"

[menu]
  
  [[menu.main]]
    name = "Posts"
    weight = 10
    identifier = "posts"
    url = "/posts/"

  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 20
    url = "/about/"

# [taxonomies]
#   category = "categories"
#   series = "series"
#   tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'bw'
    tabWidth = 2

[server]
  [[server.headers]]
    for = '/**'
      [server.headers.values]
        Strict-Transport-Security = "max-age=31536000; includeSubDomains"
        # For CSP see https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
        Content-Security-Policy = "default-src 'self' *.zgo.at *.goatcounter.com"
        X-Frame-Options = "SAMEORIGIN"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "strict-origin-when-cross-origin"
        Permissions-Policy = "microphone=(), camera=()"
        
        
        